DATA:
  ROOT: "/data1/ChaLearnLCFull"
  TRAIN_IMG_DATA: "train_data"
  VALID_IMG_DATA: "valid_data"
  TEST_IMG_DATA: "test_data"
  TRAIN_IMG_FACE_DATA: "train_data_face_decomposed/albedo"
  VALID_IMG_FACE_DATA: "valid_data_face_decomposed/albedo"
  TEST_IMG_FACE_DATA: "test_data_face_decomposed/albedo"
  TRAIN_AUD_DATA: "voice_data/voice_librosa/train_data"
  VALID_AUD_DATA: "voice_data/voice_librosa/valid_data"
  TEST_AUD_DATA: "voice_data/voice_librosa/test_data"
  TRAIN_LABEL_DATA: "annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "annotation/annotation_test.pkl"
DATA_LOADER:
  NAME: "crnet_data_loader"
  TRANSFORM: "crnet_frame_face_transform"
  TRAIN_BATCH_SIZE: 30
  VALID_BATCH_SIZE: 30
  NUM_WORKERS: 4
MODEL:
  NAME: "crnet_model"
LOSS:
  NAME: "crnet_loss_func"
SOLVER:
  NAME: "crnet_solver"
  SCHEDULER: "crnet_multi_step_scale"
  LR_INIT: 0.002
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  MILESTONE: [80, 90]
TRAIN:
  TRAINER: "CRNetTrainer2"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results/unified_frame_images/04_crnet_abl"